name: Build and Push to ACR

on:
  push:
    branches: [ main ]

env:
  IMAGE_PREFIX: dify

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push API
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_PREFIX }}-api:latest -f ./docker/api/Dockerfile .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_PREFIX }}-api:latest

    - name: Build and Push Web
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_PREFIX }}-web:latest -f ./docker/web/Dockerfile .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_PREFIX }}-web:latest
